export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const SET_LOADING = 'SET_LOADING';
export const SAVE_SEARCH_OFFERS = 'SAVE_SEARCH_OFFERS';
export const SHOW_MORE_OFFERS = 'SHOW_MORE_OFFERS';
